name: Hood
main: com.elevatemc.anticheat.Hood
version: 2.0
authors: [Saif, Beanes]
description: Advanced Cheat Detection system for ElevateMC
softdepend: [PacketEvents, ViaVersion, ProtocolLib, eLib]
load: POSTWORLD
commands:
  logs:
    description: "Logs command"
  banwave:
    description: "Banwave command"
  retard:
    description: "Shit anticheat"
  stalk:
    description: "Focus command"
  checkban:
    description: "Check bans"